// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhGJ5kYPO5n29zD-8v56rdD427A4VR6G8',
    appId: '1:902638078881:web:99b55d8dc02f0fba7a99e0',
    messagingSenderId: '902638078881',
    projectId: 'tourguard-6259b',
    authDomain: 'tourguard-6259b.firebaseapp.com',
    storageBucket: 'tourguard-6259b.firebasestorage.app',
    measurementId: 'G-X9PGZLR5WX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCumCpD_dDdy_K0pdYOYwYZ_7UiEqGjmOw',
    appId: '1:902638078881:android:89f11b9d653ab2717a99e0',
    messagingSenderId: '902638078881',
    projectId: 'tourguard-6259b',
    storageBucket: 'tourguard-6259b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzOkoCncINoFinRT3mO85dn2s3ne-tzU0',
    appId: '1:902638078881:ios:1f56bfb733fc0a6c7a99e0',
    messagingSenderId: '902638078881',
    projectId: 'tourguard-6259b',
    storageBucket: 'tourguard-6259b.firebasestorage.app',
    androidClientId: '902638078881-s9ketlbb7mkve00pgjri9lffjl1sket0.apps.googleusercontent.com',
    iosClientId: '902638078881-0a499ueu0a788eqrlfdo10oievnvubjs.apps.googleusercontent.com',
    iosBundleId: 'com.example.tourguard',
  );

}